name: "GH Arxiv Posterbot"
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 2,6,14,18,22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: scrape and run
        run: python3 paperbot.py
        env:
          BSKYBOT: ${{ secrets.BSKYBOT }}
          BSKYPWD: ${{ secrets.BSKYPWD }}
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          push: true
          default_author: github_actions
