name: "GH Arxiv Posterbot"
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0,13,15,17,19,21,23 * * *"
    - cron: "0 0,13,19 * * *"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: scrape and run in post mode
        run: python3 paperbot.py post
        env:
          BSKYBOT: ${{ secrets.BSKYBOT }}
          BSKYPWD: ${{ secrets.BSKYPWD }}
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          push: true
          default_author: github_actions

  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: scrape and run in update mode
        run: python3 paperbot.py update
        env:
          BSKYBOT: ${{ secrets.BSKYBOT }}
          BSKYPWD: ${{ secrets.BSKYPWD }}
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          push: true
          default_author: github_actions
